/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sepet_uygulama;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
/**
 *
 * @author Süleyman Doğru
 */
public class sepet_arayuz extends javax.swing.JFrame {
    ArrayList<Object[]> tumUrunler = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(sepet_arayuz.class.getName());

    /**
     * Creates new form sepet_arayuz
     */
    public sepet_arayuz() {
        initComponents();
    }
    
    private void tabloyuGuncelle() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSepet.getModel();
        model.setRowCount(0); 
    
        for (Object[] satir : tumUrunler) {
            model.addRow(satir);
        }
    
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        txtFiyat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSepet = new javax.swing.JTable();
        tabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbBeden = new javax.swing.JComboBox<>();
        cmbKumas = new javax.swing.JComboBox<>();
        cmbUretici = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbTelMarka = new javax.swing.JComboBox<>();
        txtTelModel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbEkmekTur = new javax.swing.JComboBox<>();
        txtGramaj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün Adı");

        jLabel2.setText("Fiyatı");

        txtAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdActionPerformed(evt);
            }
        });

        tblSepet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün Adı", "Ürün Türü", "Ürünün Özellikleri", "Fiyatı", "KDV'li Fiyatı"
            }
        ));
        jScrollPane1.setViewportView(tblSepet);

        cmbBeden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL" }));
        cmbBeden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBedenActionPerformed(evt);
            }
        });

        cmbKumas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pamuk", "Yün", "Polyester", "Deri", "İpek", "Kadife", "Saten" }));
        cmbKumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKumasActionPerformed(evt);
            }
        });

        cmbUretici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mavi", "Koton", "DeFacto", "Zara", "LCWaikiki", "H&M", "Avva", "Altınyıldız" }));
        cmbUretici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUreticiActionPerformed(evt);
            }
        });

        jLabel3.setText("Kumaş Türü");

        jLabel4.setText("Beden");

        jLabel5.setText("Marka");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKumas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbBeden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUretici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKumas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBeden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUretici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabPanel.addTab("Tekstil", jPanel1);

        cmbTelMarka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Samsung", "Xiamoi", "Huawei", "Oppo", "Tecno", "Reader", "Omix" }));
        cmbTelMarka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTelMarkaActionPerformed(evt);
            }
        });

        txtTelModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelModelActionPerformed(evt);
            }
        });

        jLabel6.setText("Marka");

        jLabel7.setText("Model");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTelMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelModel, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTelMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabPanel.addTab("Cep Telefonu", jPanel2);

        cmbEkmekTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beyaz", "Kepekli", "Tam Buğday", " " }));

        txtGramaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGramajActionPerformed(evt);
            }
        });

        jLabel8.setText("Ekmek Türü");

        jLabel9.setText("Gramaj");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEkmekTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGramaj, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEkmekTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGramaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabPanel.addTab("Ekmek", jPanel3);

        btnEkle.setText("Sepete Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setText("Ürün Kaldır");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnEkle)
                                .addGap(18, 18, 18)
                                .addComponent(btnSil))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtAd))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEkle)
                    .addComponent(btnSil))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.getAccessibleContext().setAccessibleName("Tekstil");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
           String ad = txtAd.getText();
        String fiyatStr = txtFiyat.getText();

        if (ad.isEmpty() || fiyatStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen İsim ve Fiyat giriniz!");
            return;
        }

        try {
            double fiyat = Double.parseDouble(fiyatStr);
            Urun urun = null;
            String turAdi = ""; 
            String urunDetayi = ""; // YENİ: Özellikleri burada toplayacağız

            int seciliSekmeIndex = tabPanel.getSelectedIndex(); 

            if (seciliSekmeIndex == 0) { // TEKSTİL
                turAdi = "Tekstil";
                String kumas = cmbKumas.getSelectedItem().toString();
                String beden = cmbBeden.getSelectedItem().toString();
                String uretici = cmbUretici.getSelectedItem().toString();
                
                // Detayı oluşturuyoruz: "Pamuk - L - Mavi" gibi görünecek
                urunDetayi = kumas + " / " + beden + " / " + uretici;
                
                urun = new tekstil(ad, fiyat, kumas, beden, uretici);
            } 
            else if (seciliSekmeIndex == 1) { // TELEFON
                turAdi = "Telefon";
                String marka = cmbTelMarka.getSelectedItem().toString();
                String model = txtTelModel.getText();
                
                // Detay: "Apple - iPhone 14" gibi
                urunDetayi = marka + " " + model;
                
                urun = new cep_telefonu(ad, fiyat, model, marka);
            } 
            else if (seciliSekmeIndex == 2) { // EKMEK
                turAdi = "Ekmek";
                String ekmekTuru = cmbEkmekTur.getSelectedItem().toString();
                String gramajStr = txtGramaj.getText();
                
                int gramaj = 0;
                if(!gramajStr.isEmpty()) {
                     gramaj = Integer.parseInt(gramajStr);
                }
                
                // Detay: "Tam Buğday (200gr)" gibi
                urunDetayi = ekmekTuru + " (" + gramaj + "gr)";
                
                urun = new ekmek(ad, fiyat, ekmekTuru, gramaj);
            }

            if (urun != null) {
                double sonFiyat = urun.KDV_uygula(); 

                // YENİ: Listeye urunDetayi'nı da ekliyoruz (3. sıraya)
                Object[] yeniSatir = {ad, turAdi, urunDetayi, fiyat, sonFiyat};
                
                tumUrunler.add(yeniSatir);
                tabloyuGuncelle();

                txtAd.setText("");
                txtFiyat.setText("");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen sayısal değerleri kontrol ediniz!");
        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblSepet.getModel();
        int seciliSatir = tblSepet.getSelectedRow();
        
        if (seciliSatir != -1){
            model.removeRow(seciliSatir);
            if(seciliSatir < tumUrunler.size()){
                tumUrunler.remove(seciliSatir);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silmek İçin Listeden Bir Ürün Seçin!");
        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void cmbKumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKumasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKumasActionPerformed

    private void cmbBedenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBedenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBedenActionPerformed

    private void cmbUreticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUreticiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUreticiActionPerformed

    private void txtTelModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelModelActionPerformed

    private void cmbTelMarkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTelMarkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTelMarkaActionPerformed

    private void txtGramajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGramajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGramajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new sepet_arayuz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnSil;
    private javax.swing.JComboBox<String> cmbBeden;
    private javax.swing.JComboBox<String> cmbEkmekTur;
    private javax.swing.JComboBox<String> cmbKumas;
    private javax.swing.JComboBox<String> cmbTelMarka;
    private javax.swing.JComboBox<String> cmbUretici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tblSepet;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtFiyat;
    private javax.swing.JTextField txtGramaj;
    private javax.swing.JTextField txtTelModel;
    // End of variables declaration//GEN-END:variables
}
